name: Jekyll Build and Deployment

on:
  schedule:
    # 11am UTC = 7am EST (for now...stupid DST
    - cron: 0 11 * * *
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.x
      
    - name: Build Jekyll
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build    

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: './_site'
        production-branch: master
        deploy-message: ${{ join(github.event.commits.*.message) }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
